// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum app.action_type */
type ActionType =
  | 'CREATE'
  | 'NOTIFY'
  | 'DECLARE'
  | 'VALIDATE'
  | 'REGISTER'
  | 'DUPLICATE_DETECTED'
  | 'REJECT'
  | 'MARK_AS_DUPLICATE'
  | 'ARCHIVE'
  | 'ISSUE_ADOPTION_SCHEDULE'
  | 'PRINT_CERTIFICATE'
  | 'REQUEST_CORRECTION'
  | 'CORRECT'
  | 'REJECT_CORRECTION'
  | 'APPROVE_CORRECTION'
  | 'READ'
  | 'ASSIGN'
  | 'UNASSIGN'
  | 'MARK_AS_NOT_DUPLICATE'
  | 'ESCALATE'

export default ActionType
